In [1]:
from pymatgen.io.cif import CifWriter
from pymatgen.ext.matproj import MPRester
import pymatgen.symmetry.analyzer as sa
from numpy import *
from pymatgen.core.operations import *


# Structure for material id
m = MPRester("kqOngsaR68ix5AD46")
structure = m.get_structure_by_material_id("mp-4280")
# Write to a CIF.
w = CifWriter(structure,0.1)
w.write_file('GaCuO2_mp-4280_symmetrized.cif')

#============================================================================

Op1  = SymmOp.from_xyz_string('-y-1/3,x-y+1/3,z+1/3') #15
Cu1  = [2/3,1/3,1/3]                                  #6
Cu1s = Op1.operate(Cu1)

print("atome de depart : ", Cu1)
print("atome d arrivee : ", Cu1s)
print('operation de symetrie : \n', Cu1s, '=', 
      Op1.translation_vector, "+ \n", Op1.rotation_matrix, ".", Cu1)

#============================================================================

Op2  = SymmOp.from_xyz_string('-x,-x+y,-z') #11
Ga0  = [0.,0.,1.]                           #13
Ga0s = Op2.operate(Ga0)

print("\natome de depart : ", Ga0)
print("atome d arrivee : ", Ga0s)
print('operation de symetrie : \n', Ga0s, '=', 
      Op2.translation_vector, "+ \n", Op2.rotation_matrix, ".", Ga0)

#============================================================================

Op3  = SymmOp.from_xyz_string('-x+y-1/3,-x+1/3,z+1/3') #17
Ga0  = [0.,0.,0.5]                                     #1
Ga0s = Op3.operate(Ga0)

print("\natome de depart : ", Ga0)
print("atome d arrivee : ", Ga0s)
print('operation de symetrie : \n', Ga0s, '=', 
      Op3.translation_vector, "+ \n", Op3.rotation_matrix, ".", Ga0)




atome de depart :  [0.6666666666666666, 0.3333333333333333, 0.3333333333333333]
atome d arrivee :  [-0.66666667  0.66666667  0.66666667]
operation de symetrie : 
 [-0.66666667  0.66666667  0.66666667] = [-0.33333333  0.33333333  0.33333333] + 
 [[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]] . [0.6666666666666666, 0.3333333333333333, 0.3333333333333333]

atome de depart :  [0.0, 0.0, 1.0]
atome d arrivee :  [ 0.  0. -1.]
operation de symetrie : 
 [ 0.  0. -1.] = [0. 0. 0.] + 
 [[-1.  0.  0.]
 [-1.  1.  0.]
 [ 0.  0. -1.]] . [0.0, 0.0, 1.0]

atome de depart :  [0.0, 0.0, 0.5]
atome d arrivee :  [-0.33333333  0.33333333  0.83333333]
operation de symetrie : 
 [-0.33333333  0.33333333  0.83333333] = [-0.33333333  0.33333333  0.33333333] + 
 [[-1.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]] . [0.0, 0.0, 0.5]


In [2]:
%%html
<img src = "Sym1.jpg",width=200,height=200>

In [3]:
%%html
<img src = "Sym2.jpg",width=200,height=200>

In [4]:
%%html
<img src = "Sym3.jpg",width=200,height=200>